# Preprocessing

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv("c:/users/fre_f/ARVOproject/BLclinicalremoved.csv", index_col = "ID", encoding="ansi")
df1.head()

MeiboODinf-0  MeiboOSinf-0  Kjønn M=0  Alder  Synskorr.kir  Keratoconus  \
ID                                                                            
1            2.0           2.0          1     56             0            0   
2            4.0           4.0          1     74             0            0   
3            2.0           2.0          1     52             0            0   
4            3.0           2.0          1     48             0            0   
5            2.0           2.0          1     68             0            0   

    Cataract opr/linsebytte  Glaucom  Blepharoplastikk  Retinol  ...  \
ID                                                               ...   
1                         0        0                 0        0  ...   
2                         0        0                 1        0  ...   
3                         0        0                 0        0  ...   
4                         0        0                 0        0  ...   
5                         0        0                 0        0  ...   

    Kunstig tårevæske-0  RensVarme  Betennelsesdempende-0  Tåreplugger-0  \
ID                                                                         
1                     0          0                      0              0   
2                     3          0                      0              0   
3                     0          0                      3              0   
4                     5          0                      0              0   
5                     6          0                      0              0   

    Lysbehandling-0  Skjermbruk-0  Kontaktlinser-0  Mascara-0  Eyeliner-0  \
ID                                                                          
1                 0             1                0          1           1   
2                 0             1                0          1           1   
3                 0             1                0          0           0   
4                 0             1                1          1           1   
5                 0             1                0          0           1   

    AC-0  
ID        
1      1  
2      1  
3      0  
4      0  
5      1  

[5 rows x 92 columns]

In [3]:
df1.dtypes

MeiboODinf-0       float64
MeiboOSinf-0       float64
Kjønn M=0            int64
Alder                int64
Synskorr.kir         int64
                    ...   
Skjermbruk-0         int64
Kontaktlinser-0      int64
Mascara-0            int64
Eyeliner-0           int64
AC-0                 int64
Length: 92, dtype: object

In [4]:
df1["Vinter"].unique()
df1["RensVarme"].unique()

array(['0', '2', '7', '4', '5', '6', '3', '1', '8', '9', '10', ' '],
      dtype=object)

In [5]:
#Remove empty strings
df1['Vinter'] = df1['Vinter'].replace(" ", np.nan)
df1['RensVarme'] = df1['RensVarme'].replace(" ", np.nan)

In [6]:
df1["Vinter"].unique()
df1["RensVarme"].unique()

array(['0', '2', '7', '4', '5', '6', '3', '1', '8', '9', '10', nan],
      dtype=object)

In [7]:
#Convert dtype
df1['RensVarme']=df1['RensVarme'].astype('float')
df1['Vinter']=df1['Vinter'].astype('float')

In [8]:
df1['MeiboODinf-0'].unique()


array([ 2.,  4.,  3.,  1., nan,  0.])

In [9]:
df1["MeiboODinf-0"].value_counts()

2.0    215
3.0    183
4.0    129
1.0     44
0.0      2
Name: MeiboODinf-0, dtype: int64

In [10]:
#Implement class 0 in class 1
df1['MeiboODinf-0'] = df1['MeiboODinf-0'].replace(0, 1)
df1['MeiboOSinf-0'] = df1['MeiboOSinf-0'].replace(0, 1)

In [11]:
df1.shape

(582, 92)

In [12]:
df1 = df1.dropna(axis=0, subset=["MeiboODinf-0"])
df1 = df1.dropna(axis=0, subset=["MeiboOSinf-0"])

In [13]:
df1.shape

(573, 92)

In [14]:
df1['MeiboODinf-0'].unique()
df1['MeiboOSinf-0'].unique()

array([2., 4., 3., 1.])

In [15]:
df1.iloc[:,2:92]

Kjønn M=0  Alder  Synskorr.kir  Keratoconus  Cataract opr/linsebytte  \
ID                                                                          
1            1     56             0            0                        0   
2            1     74             0            0                        0   
3            1     52             0            0                        0   
4            1     48             0            0                        0   
5            1     68             0            0                        0   
..         ...    ...           ...          ...                      ...   
578          0     44             0            0                        0   
579          1     54             0            0                        0   
580          1     44             0            0                        0   
581          0     28             0            0                        0   
582          1     66             0            0                        0   

     Glaucom  Blepharoplastikk  Retinol  Antidepressiva  SS  ...  \
ID                                                           ...   
1          0                 0        0               0   0  ...   
2          0                 1        0               0   0  ...   
3          0                 0        0               0   0  ...   
4          0                 0        0               0   0  ...   
5          0                 0        0               0   0  ...   
..       ...               ...      ...             ...  ..  ...   
578        0                 0        0               0   0  ...   
579        0                 0        0               0   0  ...   
580        0                 0        0               0   0  ...   
581        0                 0        0               0   0  ...   
582        0                 0        0               0   0  ...   

     Kunstig tårevæske-0  RensVarme  Betennelsesdempende-0  Tåreplugger-0  \
ID                                                                          
1                      0        0.0                      0              0   
2                      3        0.0                      0              0   
3                      0        0.0                      3              0   
4                      5        0.0                      0              0   
5                      6        0.0                      0              0   
..                   ...        ...                    ...            ...   
578                    6        5.0                      7              0   
579                    5        0.0                      0              0   
580                    5        5.0                      7              0   
581                    3        0.0                      0              0   
582                    0        0.0                      0              0   

     Lysbehandling-0  Skjermbruk-0  Kontaktlinser-0  Mascara-0  Eyeliner-0  \
ID                                                                           
1                  0             1                0          1           1   
2                  0             1                0          1           1   
3                  0             1                0          0           0   
4                  0             1                1          1           1   
5                  0             1                0          0           1   
..               ...           ...              ...        ...         ...   
578                0             1                0          0           0   
579                0             0                0          0           0   
580                6             1                1          1           0   
581                0             1                0          0           0   
582                0             1                0          0           0   

     AC-0  
ID         
1       1  
2       1  
3       0  
4       0  
5       1  
..    ...  
578  

In [16]:
#imp = SimpleImputer(strategy='mean')
#imp = IterativeImputer(random_state=42, max_iter=100)
imp = KNNImputer(n_neighbors=3, weights="uniform")
df_imputed = imp.fit_transform(df1)
df2 = pd.DataFrame(df_imputed, columns = df1.columns.tolist(), index = df1.index)
df2

MeiboODinf-0  MeiboOSinf-0  Kjønn M=0  Alder  Synskorr.kir  Keratoconus  \
ID                                                                             
1             2.0           2.0        1.0   56.0           0.0          0.0   
2             4.0           4.0        1.0   74.0           0.0          0.0   
3             2.0           2.0        1.0   52.0           0.0          0.0   
4             3.0           2.0        1.0   48.0           0.0          0.0   
5             2.0           2.0        1.0   68.0           0.0          0.0   
..            ...           ...        ...    ...           ...          ...   
578           4.0           4.0        0.0   44.0           0.0          0.0   
579           2.0           2.0        1.0   54.0           0.0          0.0   
580           3.0           4.0        1.0   44.0           0.0          0.0   
581           2.0           2.0        0.0   28.0           0.0          0.0   
582           3.0           4.0        1.0   66.0           0.0          0.0   

     Cataract opr/linsebytte  Glaucom  Blepharoplastikk  Retinol  ...  \
ID                                                                ...   
1                        0.0      0.0               0.0      0.0  ...   
2                        0.0      0.0               1.0      0.0  ...   
3                        0.0      0.0               0.0      0.0  ...   
4                        0.0      0.0               0.0      0.0  ...   
5                        0.0      0.0               0.0      0.0  ...   
..                       ...      ...               ...      ...  ...   
578                      0.0      0.0               0.0      0.0  ...   
579                      0.0      0.0               0.0      0.0  ...   
580                      0.0      0.0               0.0      0.0  ...   
581                      0.0      0.0               0.0      0.0  ...   
582                      0.0      0.0               0.0      0.0  ...   

     Kunstig tårevæske-0  RensVarme  Betennelsesdempende-0  Tåreplugger-0  \
ID                                                                          
1                    0.0        0.0                    0.0            0.0   
2                    3.0        0.0                    0.0            0.0   
3                    0.0        0.0                    3.0            0.0   
4                    5.0        0.0                    0.0            0.0   
5                    6.0        0.0                    0.0            0.0   
..                   ...        ...                    ...            ...   
578                  6.0        5.0                    7.0            0.0   
579                  5.0        0.0                    0.0            0.0   
580                  5.0        5.0                    7.0            0.0   
581                  3.0        0.0                    0.0            0.0   
582                  0.0        0.0                    0.0            0.0   

     Lysbehandling-0  Skjermbruk-0  Kontaktlinser-0  Mascara-0  Eyeliner-0  \
ID                                                                           
1                0.0           1.0              0.0        1.0         1.0   
2                0.0           1.0              0.0        1.0         1.0   
3                0.0           1.0              0.0        0.0         0.0   
4                0.0           1.0              1.0        1.0         1.0   
5                0.0           1.0              0.0        0.0         1.0   
..               ...           ...              ...        ...         ...   
578              0.0           1.0              0.0        0.0         0.0   
579              0.0           0.0              0.0        0.0         0.0   
580              6.0           1.0              1.0        1.0         0.0   
581              0.0           1.0              0.0        0.0         0.0   
582              0.0           1.0              0.0        0.0         0.0  

In [17]:
#print(df2)

In [18]:
#Using Pearson Correlation
#plt.figure(figsize=(12,10))
#cor = df2.corr()
#sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
#plt.show()

In [19]:
type(df2)

pandas.core.frame.DataFrame

In [20]:
#df2.iloc[:,0:47]

In [21]:
df2.iloc[:,0]

ID
1      2.0
2      4.0
3      2.0
4      3.0
5      2.0
      ... 
578    4.0
579    2.0
580    3.0
581    2.0
582    3.0
Name: MeiboODinf-0, Length: 573, dtype: float64

In [22]:
df2.iloc[:,2:] 

Kjønn M=0  Alder  Synskorr.kir  Keratoconus  Cataract opr/linsebytte  \
ID                                                                          
1          1.0   56.0           0.0          0.0                      0.0   
2          1.0   74.0           0.0          0.0                      0.0   
3          1.0   52.0           0.0          0.0                      0.0   
4          1.0   48.0           0.0          0.0                      0.0   
5          1.0   68.0           0.0          0.0                      0.0   
..         ...    ...           ...          ...                      ...   
578        0.0   44.0           0.0          0.0                      0.0   
579        1.0   54.0           0.0          0.0                      0.0   
580        1.0   44.0           0.0          0.0                      0.0   
581        0.0   28.0           0.0          0.0                      0.0   
582        1.0   66.0           0.0          0.0                      0.0   

     Glaucom  Blepharoplastikk  Retinol  Antidepressiva   SS  ...  \
ID                                                            ...   
1        0.0               0.0      0.0             0.0  0.0  ...   
2        0.0               1.0      0.0             0.0  0.0  ...   
3        0.0               0.0      0.0             0.0  0.0  ...   
4        0.0               0.0      0.0             0.0  0.0  ...   
5        0.0               0.0      0.0             0.0  0.0  ...   
..       ...               ...      ...             ...  ...  ...   
578      0.0               0.0      0.0             0.0  0.0  ...   
579      0.0               0.0      0.0             0.0  0.0  ...   
580      0.0               0.0      0.0             0.0  0.0  ...   
581      0.0               0.0      0.0             0.0  0.0  ...   
582      0.0               0.0      0.0             0.0  0.0  ...   

     Kunstig tårevæske-0  RensVarme  Betennelsesdempende-0  Tåreplugger-0  \
ID                                                                          
1                    0.0        0.0                    0.0            0.0   
2                    3.0        0.0                    0.0            0.0   
3                    0.0        0.0                    3.0            0.0   
4                    5.0        0.0                    0.0            0.0   
5                    6.0        0.0                    0.0            0.0   
..                   ...        ...                    ...            ...   
578                  6.0        5.0                    7.0            0.0   
579                  5.0        0.0                    0.0            0.0   
580                  5.0        5.0                    7.0            0.0   
581                  3.0        0.0                    0.0            0.0   
582                  0.0        0.0                    0.0            0.0   

     Lysbehandling-0  Skjermbruk-0  Kontaktlinser-0  Mascara-0  Eyeliner-0  \
ID                                                                           
1                0.0           1.0              0.0        1.0         1.0   
2                0.0           1.0              0.0        1.0         1.0   
3                0.0           1.0              0.0        0.0         0.0   
4                0.0           1.0              1.0        1.0         1.0   
5                0.0           1.0              0.0        0.0         1.0   
..               ...           ...              ...        ...         ...   
578              0.0           1.0              0.0        0.0         0.0   
579              0.0           0.0              0.0        0.0         0.0   
580              6.0           1.0              1.0        1.0         0.0   
581              0.0           1.0              0.0        0.0         0.0   
582              0.0           1.0              0.0        0.0         0.0   

     AC-0  
ID         
1     1.0  
2     1.0  
3     0.0  
4     0.0  
5     1.0  
..  

In [23]:
#plt.hist(df2[47], bins=5)

In [24]:
X = df2.iloc[:,2:]


In [25]:
y = df2.iloc[:,0]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)


In [27]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(458, 90)
(115, 90)
(458,)
(115,)


In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_trainScaled = scaler.fit_transform(X_train)
X_testScaled = scaler.transform(X_test)
X_trainScaled = pd.DataFrame(X_trainScaled, columns = X_train.columns.tolist(), index=X_train.index)
X_testScaled = pd.DataFrame(X_testScaled, columns = X_test.columns.tolist(), index=X_test.index)

In [29]:
#X_trainScaled

In [30]:
print(X_trainScaled.shape)
print(X_testScaled.shape)
print(y_train.shape)
print(y_test.shape)

(458, 90)
(115, 90)
(458,)
(115,)


In [31]:
def metrics():
    y_pred = clf.predict(X_testScaled)
    bal_acc = balanced_accuracy_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    cf = confusion_matrix(y_test, y_pred)
    target_names = ['class 0/1', 'class 2', 'class 3', 'class 4']
    print(f"Balanced accuracy: {bal_acc}")
    print(f"MCC: {mcc}")
    print(f"F1: {f1}")
    print(f"Confusion matrix: \n{cf}")
    print(f"Classification report: \n{classification_report(y_test, y_pred, target_names=target_names)}")

In [32]:
def complete_output():
    np.set_printoptions(threshold=np.inf)
    pd.set_option('display.max_rows', 200)
    y_pred = clf.predict(X_testScaled)
    list_a = [print(f"proba: \n{clf.predict_proba(X_testScaled)}")]
    list_b = [print(f"y_pred: \n{y_pred}")]
    list_c = [print(f"y_test: \n{y_test}")]
    lists = [list_a, list_b, list_c]
    for x in zip(*lists):
        print(*x)

# Training and predicting on the right eye

In [33]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier(strategy="most_frequent")
clf.fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()


Balanced accuracy: 0.25
MCC: 0.0
F1: 0.15151515151515152
Confusion matrix: 
[[ 0  6  0  0]
 [ 0 50  0  0]
 [ 0 41  0  0]
 [ 0 18  0  0]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.00      0.00      0.00         6
     class 2       0.43      1.00      0.61        50
     class 3       0.00      0.00      0.00        41
     class 4       0.00      0.00      0.00        18

    accuracy                           0.43       115
   macro avg       0.11      0.25      0.15       115
weighted avg       0.19      0.43      0.26       115



C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
from sklearn.svm import LinearSVC
clf = LinearSVC(max_iter=5000).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.35814363143631434
MCC: 0.0960493705075696
F1: 0.33986928104575165
Confusion matrix: 
[[ 2  4  0  0]
 [ 4 24 14  8]
 [ 3 15 14  9]
 [ 1  9  3  5]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.20      0.33      0.25         6
     class 2       0.46      0.48      0.47        50
     class 3       0.45      0.34      0.39        41
     class 4       0.23      0.28      0.25        18

    accuracy                           0.39       115
   macro avg       0.34      0.36      0.34       115
weighted avg       0.41      0.39      0.40       115



C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [35]:
clf = RandomForestClassifier().fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.3692682926829268
MCC: 0.14224865328701478
F1: 0.3881376724118659
Confusion matrix: 
[[ 1  4  1  0]
 [ 1 33 14  2]
 [ 0 23 13  5]
 [ 0  7  5  6]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.50      0.17      0.25         6
     class 2       0.49      0.66      0.56        50
     class 3       0.39      0.32      0.35        41
     class 4       0.46      0.33      0.39        18

    accuracy                           0.46       115
   macro avg       0.46      0.37      0.39       115
weighted avg       0.45      0.46      0.44       115



In [36]:
clf = RandomForestClassifier(n_estimators=5000, criterion="gini", bootstrap=True, oob_score=False, warm_start=False, random_state=42).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.3386991869918699
MCC: 0.15709008525377932
F1: 0.3323577830620084
Confusion matrix: 
[[ 0  6  0  0]
 [ 1 34 11  4]
 [ 0 22 14  5]
 [ 0  7  5  6]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.00      0.00      0.00         6
     class 2       0.49      0.68      0.57        50
     class 3       0.47      0.34      0.39        41
     class 4       0.40      0.33      0.36        18

    accuracy                           0.47       115
   macro avg       0.34      0.34      0.33       115
weighted avg       0.44      0.47      0.45       115



In [37]:
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=1000, bootstrap=True, oob_score=True, random_state=42).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.35208672086720866
MCC: 0.1674236592624477
F1: 0.3338146508878216
Confusion matrix: 
[[ 0  6  0  0]
 [ 1 36  9  4]
 [ 0 24 10  7]
 [ 0  7  3  8]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.00      0.00      0.00         6
     class 2       0.49      0.72      0.59        50
     class 3       0.45      0.24      0.32        41
     class 4       0.42      0.44      0.43        18

    accuracy                           0.47       115
   macro avg       0.34      0.35      0.33       115
weighted avg       0.44      0.47      0.44       115



In [38]:
neigh = KNeighborsClassifier(n_neighbors=3)
clf = neigh.fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.2881707317073171
MCC: -0.028047373381555274
F1: 0.2611607142857143
Confusion matrix: 
[[ 2  4  0  0]
 [10 18 18  4]
 [ 3 19 12  7]
 [ 1  8  6  3]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.12      0.33      0.18         6
     class 2       0.37      0.36      0.36        50
     class 3       0.33      0.29      0.31        41
     class 4       0.21      0.17      0.19        18

    accuracy                           0.30       115
   macro avg       0.26      0.29      0.26       115
weighted avg       0.32      0.30      0.31       115



In [39]:
# lbfgs, sgd, adam
#logistic, tanh, relu
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver="adam", activation="relu", learning_rate="constant", random_state=42, max_iter=3000, verbose=False).fit(X_trainScaled, y_train)
clf.out_activation_="softmax"
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.4614769647696477
MCC: 0.16276792744794044
F1: 0.4236681887366819
Confusion matrix: 
[[ 4  1  1  0]
 [ 3 28 12  7]
 [ 2 19 14  6]
 [ 1  7  5  5]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.40      0.67      0.50         6
     class 2       0.51      0.56      0.53        50
     class 3       0.44      0.34      0.38        41
     class 4       0.28      0.28      0.28        18

    accuracy                           0.44       115
   macro avg       0.41      0.46      0.42       115
weighted avg       0.44      0.44      0.44       115



In [40]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=50, random_state=42).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()
#complete_output()

Balanced accuracy: 0.4481571815718157
MCC: 0.14974045689608148
F1: 0.4040920983778127
Confusion matrix: 
[[ 3  3  0  0]
 [ 3 21 16 10]
 [ 3 14 13 11]
 [ 0  3  5 10]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.33      0.50      0.40         6
     class 2       0.51      0.42      0.46        50
     class 3       0.38      0.32      0.35        41
     class 4       0.32      0.56      0.41        18

    accuracy                           0.41       115
   macro avg       0.39      0.45      0.40       115
weighted avg       0.43      0.41      0.41       115



In [41]:
from sklearn.ensemble import HistGradientBoostingClassifier
clf = HistGradientBoostingClassifier().fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()
#complete_output()

Balanced accuracy: 0.4881571815718157
MCC: 0.17721070245927809
F1: 0.4662246204499726
Confusion matrix: 
[[ 4  2  0  0]
 [ 3 29 13  5]
 [ 1 22 13  5]
 [ 0  7  4  7]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.50      0.67      0.57         6
     class 2       0.48      0.58      0.53        50
     class 3       0.43      0.32      0.37        41
     class 4       0.41      0.39      0.40        18

    accuracy                           0.46       115
   macro avg       0.46      0.49      0.47       115
weighted avg       0.46      0.46      0.45       115



In [42]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=1.0, max_depth=None, random_state=42).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.3565311653116531
MCC: 0.07214025539457673
F1: 0.3321637426900585
Confusion matrix: 
[[ 2  4  0  0]
 [ 3 23 17  7]
 [ 2 16 10 13]
 [ 2  2  7  7]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.22      0.33      0.27         6
     class 2       0.51      0.46      0.48        50
     class 3       0.29      0.24      0.27        41
     class 4       0.26      0.39      0.31        18

    accuracy                           0.37       115
   macro avg       0.32      0.36      0.33       115
weighted avg       0.38      0.37      0.37       115



In [43]:
from xgboost import XGBClassifier
clf = XGBClassifier(max_depth=10, eta=0.3, reg_lambda=50, alpha=0).fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.43481029810298105
MCC: 0.19877279850012866
F1: 0.43710944483848846
Confusion matrix: 
[[ 2  3  1  0]
 [ 2 31 14  3]
 [ 1 18 14  8]
 [ 0  7  3  8]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.40      0.33      0.36         6
     class 2       0.53      0.62      0.57        50
     class 3       0.44      0.34      0.38        41
     class 4       0.42      0.44      0.43        18

    accuracy                           0.48       115
   macro avg       0.45      0.43      0.44       115
weighted avg       0.47      0.48      0.47       115



In [44]:
import lightgbm as lgb
from lightgbm import LGBMClassifier
clf = LGBMClassifier().fit(X_trainScaled, y_train)
clf.predict(X_testScaled)

metrics()

Balanced accuracy: 0.49925474254742547
MCC: 0.19641485813097306
F1: 0.49918678739101274
Confusion matrix: 
[[ 4  2  0  0]
 [ 2 30 13  5]
 [ 0 22 14  5]
 [ 0  8  3  7]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.67      0.67      0.67         6
     class 2       0.48      0.60      0.54        50
     class 3       0.47      0.34      0.39        41
     class 4       0.41      0.39      0.40        18

    accuracy                           0.48       115
   macro avg       0.51      0.50      0.50       115
weighted avg       0.48      0.48      0.47       115



# Training and predicting on the left eye

In [45]:
#df2.iloc[: ,1]

In [46]:
X_OS = df2.iloc[:,2:]


In [47]:
df2.iloc[:,1]

ID
1      2.0
2      4.0
3      2.0
4      2.0
5      2.0
      ... 
578    4.0
579    2.0
580    4.0
581    2.0
582    4.0
Name: MeiboOSinf-0, Length: 573, dtype: float64

In [48]:
y_OS = df2.iloc[:,1]

In [49]:
X_trainOS, X_testOS, y_trainOS, y_testOS = train_test_split(X_OS, y_OS, test_size = 0.2, random_state=42)


In [50]:
scaler = StandardScaler()
X_trainScaledOS = scaler.fit_transform(X_trainOS)
X_testScaledOS = scaler.transform(X_testOS)
X_trainScaledOS = pd.DataFrame(X_trainScaledOS, columns = X_trainOS.columns.tolist(), index=X_trainOS.index)
X_testScaledOS = pd.DataFrame(X_testScaledOS, columns = X_testOS.columns.tolist(), index=X_testOS.index)

In [51]:
type(X_trainScaledOS)
type(X_testScaledOS)

pandas.core.frame.DataFrame

In [52]:
print(X_trainScaledOS.shape)
print(X_testScaledOS.shape)
print(y_trainOS.shape)
print(y_testOS.shape)

(458, 90)
(115, 90)
(458,)
(115,)


In [53]:
#X_trainScaledOS

In [54]:
def metricsOS():
    y_predOS = clf.predict(X_testScaledOS)
    bal_acc = balanced_accuracy_score(y_testOS, y_predOS)
    mcc = matthews_corrcoef(y_testOS, y_predOS)
    f1 = f1_score(y_testOS, y_predOS, average="macro")
    cf = confusion_matrix(y_testOS, y_predOS)
    target_names = ['class 0/1', 'class 2', 'class 3', 'class 4']
    print(f"Balanced accuracy: {bal_acc}")
    print(f"MCC: {mcc}")
    print(f"F1: {f1}")
    print(f"Confusion matrix: \n{cf}")
    print(f"Classification report: \n{classification_report(y_testOS, y_predOS, target_names=target_names)}")

In [55]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier(strategy="most_frequent")
clf.fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.25
MCC: 0.0
F1: 0.13836477987421383
Confusion matrix: 
[[ 0  8  0  0]
 [ 0 44  0  0]
 [ 0 34  0  0]
 [ 0 29  0  0]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.00      0.00      0.00         8
     class 2       0.38      1.00      0.55        44
     class 3       0.00      0.00      0.00        34
     class 4       0.00      0.00      0.00        29

    accuracy                           0.38       115
   macro avg       0.10      0.25      0.14       115
weighted avg       0.15      0.38      0.21       115



C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [56]:
from sklearn.svm import LinearSVC
clf = LinearSVC(max_iter=5000).fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.2729808224230131
MCC: -0.001067919936021542
F1: 0.2608788180588548
Confusion matrix: 
[[ 2  2  2  2]
 [ 7 15 16  6]
 [ 2 13 10  9]
 [ 4 10  9  6]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.13      0.25      0.17         8
     class 2       0.38      0.34      0.36        44
     class 3       0.27      0.29      0.28        34
     class 4       0.26      0.21      0.23        29

    accuracy                           0.29       115
   macro avg       0.26      0.27      0.26       115
weighted avg       0.30      0.29      0.29       115



C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [57]:
clf = RandomForestClassifier().fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.34525977318827217
MCC: 0.1367745787705434
F1: 0.35221068301138436
Confusion matrix: 
[[ 1  5  1  1]
 [ 0 28  9  7]
 [ 0 17  7 10]
 [ 0 10  7 12]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       1.00      0.12      0.22         8
     class 2       0.47      0.64      0.54        44
     class 3       0.29      0.21      0.24        34
     class 4       0.40      0.41      0.41        29

    accuracy                           0.42       115
   macro avg       0.54      0.35      0.35       115
weighted avg       0.44      0.42      0.40       115



In [58]:
clf = RandomForestClassifier(n_estimators=5000, criterion="gini", bootstrap=True, oob_score=False, warm_start=True, random_state=42).fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.28225843628987646
MCC: 0.05781845670101262
F1: 0.26124017568192326
Confusion matrix: 
[[ 0  7  0  1]
 [ 0 25 11  8]
 [ 0 16  5 13]
 [ 0 11  6 12]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.00      0.00      0.00         8
     class 2       0.42      0.57      0.49        44
     class 3       0.23      0.15      0.18        34
     class 4       0.35      0.41      0.38        29

    accuracy                           0.37       115
   macro avg       0.25      0.28      0.26       115
weighted avg       0.32      0.37      0.33       115



C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fre_f\anaconda3\envs\FF\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
neigh = KNeighborsClassifier(n_neighbors=3)
clf = neigh.fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.32871565554121335
MCC: 0.08285103423005225
F1: 0.322917476860854
Confusion matrix: 
[[ 2  2  2  2]
 [ 7 17 16  4]
 [ 5 15  9  5]
 [ 1  8  8 12]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.13      0.25      0.17         8
     class 2       0.40      0.39      0.40        44
     class 3       0.26      0.26      0.26        34
     class 4       0.52      0.41      0.46        29

    accuracy                           0.35       115
   macro avg       0.33      0.33      0.32       115
weighted avg       0.37      0.35      0.36       115



In [60]:
# lbfgs, sgd, adam
#logistic, tanh, relu
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver="adam", activation="relu", learning_rate="constant", random_state=42, max_iter=3000, verbose=False).fit(X_trainScaledOS, y_trainOS)
clf.out_activation_="softmax"
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.34222293933247283
MCC: 0.09997843505790185
F1: 0.34066016771168645
Confusion matrix: 
[[ 2  4  2  0]
 [ 4 25  8  7]
 [ 1 17  7  9]
 [ 0 11  8 10]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.29      0.25      0.27         8
     class 2       0.44      0.57      0.50        44
     class 3       0.28      0.21      0.24        34
     class 4       0.38      0.34      0.36        29

    accuracy                           0.38       115
   macro avg       0.35      0.34      0.34       115
weighted avg       0.37      0.38      0.37       115



In [61]:
from sklearn.ensemble import AdaBoostClassifier
clfAdaOS = AdaBoostClassifier(n_estimators=50, random_state=42).fit(X_trainScaledOS, y_trainOS)
clfAdaOS.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.34222293933247283
MCC: 0.09997843505790185
F1: 0.34066016771168645
Confusion matrix: 
[[ 2  4  2  0]
 [ 4 25  8  7]
 [ 1 17  7  9]
 [ 0 11  8 10]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.29      0.25      0.27         8
     class 2       0.44      0.57      0.50        44
     class 3       0.28      0.21      0.24        34
     class 4       0.38      0.34      0.36        29

    accuracy                           0.38       115
   macro avg       0.35      0.34      0.34       115
weighted avg       0.37      0.38      0.37       115



In [62]:
from sklearn.ensemble import HistGradientBoostingClassifier
clf = HistGradientBoostingClassifier().fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.34449336160796606
MCC: 0.09060010677818675
F1: 0.36589634401306015
Confusion matrix: 
[[ 2  5  1  0]
 [ 1 20 13 10]
 [ 0 13 10 11]
 [ 0  7 11 11]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.67      0.25      0.36         8
     class 2       0.44      0.45      0.45        44
     class 3       0.29      0.29      0.29        34
     class 4       0.34      0.38      0.36        29

    accuracy                           0.37       115
   macro avg       0.44      0.34      0.37       115
weighted avg       0.39      0.37      0.37       115



In [63]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.5, max_depth=None, random_state=42).fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.2885798912041305
MCC: 0.03449599289660059
F1: 0.2868761199973452
Confusion matrix: 
[[ 1  2  5  0]
 [ 2 12 17 13]
 [ 2  9 14  9]
 [ 0  9 10 10]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.20      0.12      0.15         8
     class 2       0.38      0.27      0.32        44
     class 3       0.30      0.41      0.35        34
     class 4       0.31      0.34      0.33        29

    accuracy                           0.32       115
   macro avg       0.30      0.29      0.29       115
weighted avg       0.33      0.32      0.32       115



In [64]:
from xgboost import XGBClassifier
clf = XGBClassifier(max_depth=10, eta=0.3, reg_lambda=50, alpha=0).fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metricsOS()

Balanced accuracy: 0.32781094412686707
MCC: 0.1089290574657878
F1: 0.3271240668325631
Confusion matrix: 
[[ 1  6  1  0]
 [ 0 26  9  9]
 [ 1 14  5 14]
 [ 0  7  9 13]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.50      0.12      0.20         8
     class 2       0.49      0.59      0.54        44
     class 3       0.21      0.15      0.17        34
     class 4       0.36      0.45      0.40        29

    accuracy                           0.39       115
   macro avg       0.39      0.33      0.33       115
weighted avg       0.38      0.39      0.37       115



In [67]:
import lightgbm as lgb
from lightgbm import LGBMClassifier
clf = LGBMClassifier().fit(X_trainScaledOS, y_trainOS)
clf.predict(X_testScaledOS)

metrics()

Balanced accuracy: 0.3665311653116531
MCC: 0.09228074498741011
F1: 0.3666010065998231
Confusion matrix: 
[[ 2  3  1  0]
 [ 2 25 11 12]
 [ 0 17 10 14]
 [ 0  3  8  7]]
Classification report: 
              precision    recall  f1-score   support

   class 0/1       0.50      0.33      0.40         6
     class 2       0.52      0.50      0.51        50
     class 3       0.33      0.24      0.28        41
     class 4       0.21      0.39      0.27        18

    accuracy                           0.38       115
   macro avg       0.39      0.37      0.37       115
weighted avg       0.40      0.38      0.39       115

